# @name Register
POST http://localhost:5000/api/v1/register
Content-Type: application/json

{
  "fullName": "Jane Doe",
  "email"   : "janedoe@root.com",
  "password" : "thisisuser",
  "gender": "Female",
  "phone": "08123456784",
  "address": "Jl Pegangsaan Timur no 56"
}

###

# @name Login
POST http://localhost:5000/api/v1/login
Content-Type: application/json
//Authorization: 

{
  "email"   : "janedoe@root.com",
  "password" : "thisisuser"
}

###  

# @name getProfiles
GET http://localhost:5000/api/v1/profile
Content-Type: application/json

###  

# @name getProfile
GET http://localhost:5000/api/v1/profile/1
Content-Type: application/json

###  

# @name getProfileLiterature
GET http://localhost:5000/api/v1/profile/2/literature
Content-Type: application/json

###  

# @name updateUser
GET http://localhost:5000/api/v1/user
Content-Type: application/json

###  

# @name deleteUser
DELETE  http://localhost:5000/api/v1/user/:id
Content-Type: application/json

###

# @name getLiteratures
GET http://localhost:5000/api/v1/literatures
Content-Type: application/json

###

# @name getLiterature
GET http://localhost:5000/api/v1/literature/1
Content-Type: application/json

###  

# @name searchLiterature
GET http://localhost:5000/api/v1/literature?title=lit&public_year=2012
Content-Type: application/json



###

# @name addLiterature
POST http://localhost:5000/api/v1/literature
Content-Type: application/json 
//Authorization: 

{
	"title": "Somehow Releated",
	"userId": 2,
	"publication": "August 2020",
	"page": 123,
	"author": "Karl Donitz",
	"isbn": 15423122451,
	"file": "test.file",
	"thumbnail": "test.jpg"
}

###

# # @name editPaper
# PATCH  http://localhost:5000/api/v1/book/4
# Content-Type: application/json 
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjAyNDg4NTUyfQ.YWsOeikkf3-fvwTKRw5OhNLLi4SbzVxZlbd7Zl7WnMA

# {
# 	"title": "How to Install RAM",
# 	"author": "Pink Guy",
# 	"publication": "May 2020",
# 	"categoryId": 5,
# 	"userId": 4,
# 	"page": "250",
# 	"isbn": 123456789,
# 	"about": "Lorem Ipsum, this is just a dummy. There's nothing to see here, really.",
# 	"file": "theDominator.epub",
# 	"thumbnail": "howToInstalRAM.jpg",
# 	"status": "Waiting"
# }

###

# @name deleteLiterature
DELETE  http://localhost:5000/api/v1/literature/:id
Content-Type: application/json 
//Authorization: 

###

# @name getCollection
GET http://localhost:5000/api/v1/collection/2
Content-Type: application/json