// Admin Token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjA0NzcyMTUxfQ.rmZTVbgxumoDb4bWK_fPDtTOT_-pTrZ8CcnI1QOP6jI

// User Token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjA0NzcxMTYzfQ.C8s-fCKJLB11rC6gscYprBc3RMPjYI2ngXQ5bdtXvHc

##########################################

# @name Register
POST http://localhost:5000/api/v1/register
Content-Type: application/json

{
  "fullName": "New User",
  "email"   : "user1@root.com",
  "password" : "thisisuser",
  "gender": "Male",
  "phone": "08123456784",
  "address": "Jl Pegangsaan Timur no 56"
}

###

# @name Login
POST http://localhost:5000/api/v1/login
Content-Type: application/json
//Authorization: 

{
  "email"   : "user@root.com",
  "password" : "thisisuser"
}

###  

# @name getUsers
GET http://localhost:5000/api/v1/user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjA0NzcyMTUxfQ.rmZTVbgxumoDb4bWK_fPDtTOT_-pTrZ8CcnI1QOP6jI

###  

# @name getUser
GET http://localhost:5000/api/v1/user/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjA0NzcyMTUxfQ.rmZTVbgxumoDb4bWK_fPDtTOT_-pTrZ8CcnI1QOP6jI

###  

# @name getUserLiterature
GET http://localhost:5000/api/v1/user-literature/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjA0NzcxMTYzfQ.C8s-fCKJLB11rC6gscYprBc3RMPjYI2ngXQ5bdtXvHc

### ##########################

### MULTIFORM DATA RIGHT HERE 

### ##########################

# @name deleteUser
DELETE  http://localhost:5000/api/v1/user/6
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjA0NzcxMTYzfQ.C8s-fCKJLB11rC6gscYprBc3RMPjYI2ngXQ5bdtXvHc

###

# @name getLiteratures
GET http://localhost:5000/api/v1/literatures
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjA0NzcxMTYzfQ.C8s-fCKJLB11rC6gscYprBc3RMPjYI2ngXQ5bdtXvHc

###

# @name getLiterature
GET http://localhost:5000/api/v1/literature/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjA0NzcxMTYzfQ.C8s-fCKJLB11rC6gscYprBc3RMPjYI2ngXQ5bdtXvHc

###  

# @name searchLiterature
GET http://localhost:5000/api/v1/literature?title=si&public_year=2019
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjA0NzcxMTYzfQ.C8s-fCKJLB11rC6gscYprBc3RMPjYI2ngXQ5bdtXvHc

###  

# @name searchLiteratureByTitle
GET http://localhost:5000/api/v1/approved-literature/si
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjA0NzcxMTYzfQ.C8s-fCKJLB11rC6gscYprBc3RMPjYI2ngXQ5bdtXvHc

###  

# @name getYear
GET http://localhost:5000/api/v1/year
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjA0NzcxMTYzfQ.C8s-fCKJLB11rC6gscYprBc3RMPjYI2ngXQ5bdtXvHc

###

# @name getLiteratureByYear
GET http://localhost:5000/api/v1/approved-literature/si/2019
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjA0NzcxMTYzfQ.C8s-fCKJLB11rC6gscYprBc3RMPjYI2ngXQ5bdtXvHc

###

# @name addLiterature
POST http://localhost:5000/api/v1/literature
Content-Type: application/json 
//Authorization: 

{
	"title": "Little Child",
	"userId": 2,
	"publication": "August 2015",
	"page": 153,
	"author": "Joseph Stallin",
	"isbn": 15423122451,
	"file": "test.file",
	"thumbnail": "test.jpg"
}

###

# # @name editPaper
# PATCH  http://localhost:5000/api/v1/book/4
# Content-Type: application/json 
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjAyNDg4NTUyfQ.YWsOeikkf3-fvwTKRw5OhNLLi4SbzVxZlbd7Zl7WnMA

# {
# 	"title": "How to Install RAM",
# 	"author": "Pink Guy",
# 	"publication": "May 2020",
# 	"categoryId": 5,
# 	"userId": 4,
# 	"page": "250",
# 	"isbn": 123456789,
# 	"about": "Lorem Ipsum, this is just a dummy. There's nothing to see here, really.",
# 	"file": "theDominator.epub",
# 	"thumbnail": "howToInstalRAM.jpg",
# 	"status": "Waiting"
# }

###

# @name deleteLiterature
DELETE  http://localhost:5000/api/v1/literature/:id
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjA0NzcxMTYzfQ.C8s-fCKJLB11rC6gscYprBc3RMPjYI2ngXQ5bdtXvHc


###

# @name getCollection
GET http://localhost:5000/api/v1/collection/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjA0NzcxMTYzfQ.C8s-fCKJLB11rC6gscYprBc3RMPjYI2ngXQ5bdtXvHc


###

# @name addCollection
POST  http://localhost:5000/api/v1/collection/2
Content-Type: application/json
{
  "userId": 2,
  "literatureId": 5,
}

###

# @name deleteCollection
DELETE  http://localhost:5000/api/v1/remove-collection/6
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjA0NzcxMTYzfQ.C8s-fCKJLB11rC6gscYprBc3RMPjYI2ngXQ5bdtXvHc
